-- =============================================================================
-- DataLedger · Stage 0 数据库 Schema
-- -----------------------------------------------------------------------------
-- 目标数据库 : PostgreSQL 14+
-- 用途       : 智能问数（NL2SQL）平台的评测底座
-- 版本       : v0.1
--
-- 【设计意图 —— 这份 Schema 为什么长这样】
--
-- 它不是为了"把业务表建出来"，而是**故意保留真实数仓里最常见的口径歧义**。
-- 原因是：如果 Schema 建得干净无歧义，Text-to-SQL 就退化成字符串拼接，
-- 一个 7B 小模型也能跑出高准确率，项目也就没有难度和故事可讲。
--
-- 真实企业的痛点是：同一个问题（"上个月华东卖了多少"）在不同人嘴里
-- 对应不同的 SQL，答案能差 30%。所以这里的每一张表都埋了口径陷阱，
-- 逼着实现方必须做【语义层】而不是直接 prompt → SQL。
--
-- 全部陷阱在字段注释中标记为 [陷阱N]，与 eval/cases.yaml 一一对应，
-- 评测集里至少有 30 条用例踩中它们。
--
-- 陷阱速查表（详见文件末尾汇总）：
--   ① 大区命名不一致   ② 两级类目        ③ 成本价在商品表
--   ④ 存生日问年龄     ⑤ 注册地≠收货地    ⑥ 取消订单计入销售额
--   ⑦ 三个金额互不相等 ⑧ 时间边界        ⑨ "销量"有三种口径
--   ⑩ 明细金额加总失真 ⑪ 退货率口径      ⑫ 可空外键丢行
-- =============================================================================

-- 幂等重建（注意外键依赖顺序，用 CASCADE 兜底）
DROP TABLE IF EXISTS refunds      CASCADE;
DROP TABLE IF EXISTS order_items  CASCADE;
DROP TABLE IF EXISTS orders       CASCADE;
DROP TABLE IF EXISTS dim_customer CASCADE;
DROP TABLE IF EXISTS dim_product  CASCADE;
DROP TABLE IF EXISTS dim_region   CASCADE;


-- =============================================================================
-- 1. dim_region · 地区维表
-- =============================================================================
CREATE TABLE dim_region (
    region_id    INT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    province     VARCHAR(32)  NOT NULL,
    city         VARCHAR(32)  NOT NULL,
    region_group VARCHAR(16)  NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now()
);

COMMENT ON TABLE  dim_region              IS '地区维表：省 / 市 / 大区三级归属';
COMMENT ON COLUMN dim_region.province     IS '省级行政区全称，如「江苏省」「广东省」';
COMMENT ON COLUMN dim_region.region_group IS '[陷阱①] 大区。库里存的是「华东区」（带"区"字），而用户口语永远说「华东」。严格等值匹配 `region_group = ''华东''` 会返回 0 行，必须走语义层归一或 LIKE 处理。此坑与 dim_product.category_l1 的命名风格故意不一致（那边不带后缀）。';

CREATE INDEX idx_region_province ON dim_region (province);
CREATE INDEX idx_region_group    ON dim_region (region_group);
CREATE INDEX idx_region_city     ON dim_region (city);


-- =============================================================================
-- 2. dim_product · 商品维表
-- =============================================================================
CREATE TABLE dim_product (
    product_id   INT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(128)  NOT NULL,
    category_l1  VARCHAR(32)   NOT NULL,
    category_l2  VARCHAR(32)   NOT NULL,
    brand        VARCHAR(32)   NOT NULL,
    list_price   NUMERIC(10,2) NOT NULL,
    cost_price   NUMERIC(10,2) NOT NULL,
    launch_date  DATE          NOT NULL,
    is_active    BOOLEAN       NOT NULL DEFAULT TRUE
);

COMMENT ON TABLE  dim_product              IS '商品维表：含类目、品牌、价格与成本';
COMMENT ON COLUMN dim_product.category_l1  IS '[陷阱②] 一级类目（服装/食品/数码/家居/美妆）。用户问「服装卖得怎么样」指的是这一列。';
COMMENT ON COLUMN dim_product.category_l2  IS '[陷阱②] 二级类目（男装/女装/零食/生鲜…）。用户问「男装」指的是这一列。LLM 必须判断问题落在哪一级，选错列答案直接跑偏，且两种写法都能执行成功（不报错），是最隐蔽的一类错。';
COMMENT ON COLUMN dim_product.list_price   IS '吊牌价（标价），≠ 实际成交价。成交价在 order_items.unit_price。';
COMMENT ON COLUMN dim_product.cost_price   IS '[陷阱③] 成本价。用户问「毛利率」时，很多人会去订单表找成本，但订单表只有收入没有成本 —— 必须 join 到本表才能算出毛利。这是「跨表口径」的典型考点。';
COMMENT ON COLUMN dim_product.launch_date  IS '上架日期。用于「今年新品」这类口径，注意是 DATE 不含时间。';

CREATE INDEX idx_product_cat_l1 ON dim_product (category_l1);
CREATE INDEX idx_product_cat_l2 ON dim_product (category_l2);
CREATE INDEX idx_product_brand  ON dim_product (brand);


-- =============================================================================
-- 3. dim_customer · 用户维表
-- =============================================================================
CREATE TABLE dim_customer (
    customer_id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name VARCHAR(64)  NOT NULL,
    gender        VARCHAR(8)   NOT NULL,
    birth_date    DATE,
    register_date DATE         NOT NULL,
    member_level  VARCHAR(16)  NOT NULL,
    region_id     INT          NOT NULL,

    CONSTRAINT fk_customer_region FOREIGN KEY (region_id)
        REFERENCES dim_region (region_id)
);

COMMENT ON TABLE  dim_customer               IS '用户维表：画像、注册信息与会员等级';
COMMENT ON COLUMN dim_customer.gender        IS '[陷阱④] 取值 ''男''/''女''/''未知''（三态，不是二态）。注意"未知"约 3%，做性别占比时分母该不该含它会影响结果。';
COMMENT ON COLUMN dim_customer.birth_date    IS '[陷阱④] 存的是出生日期不是年龄，且允许 NULL。用户问「30 岁以上用户」，正确做法是换算成 `birth_date <= CURRENT_DATE - INTERVAL ''30 years''`；直接写 `age > 30` 会因为库里没有 age 列而报错。同时 NULL 行不进任何区间，分母失真。';
COMMENT ON COLUMN dim_customer.region_id     IS '[陷阱⑤] 注册地，不是收货地。用户问「华东的用户」时，如果他关心的是"人在哪收货"，应该用 orders.region_id；如果关心的是"人在哪注册"，用本列。两个口径答案不同（约 15% 的订单跨区收货），必须由语义层确认或至少显式声明假设。';
COMMENT ON COLUMN dim_customer.member_level  IS '会员等级：普通/银牌/金牌/钻石。';

CREATE INDEX idx_customer_region   ON dim_customer (region_id);
CREATE INDEX idx_customer_reg_date ON dim_customer (register_date);
CREATE INDEX idx_customer_level    ON dim_customer (member_level);


-- =============================================================================
-- 4. orders · 订单主表
-- =============================================================================
CREATE TABLE orders (
    order_id        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no        VARCHAR(32)   NOT NULL UNIQUE,
    customer_id     BIGINT        NOT NULL,
    region_id       INT           NOT NULL,
    order_time      TIMESTAMP     NOT NULL,
    order_status    VARCHAR(16)   NOT NULL,
    total_amount    NUMERIC(12,2) NOT NULL,
    discount_amount NUMERIC(12,2) NOT NULL,
    pay_amount      NUMERIC(12,2) NOT NULL,
    channel         VARCHAR(16)   NOT NULL,

    CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id)
        REFERENCES dim_customer (customer_id),
    CONSTRAINT fk_orders_region   FOREIGN KEY (region_id)
        REFERENCES dim_region (region_id),
    CONSTRAINT ck_orders_amounts  CHECK (total_amount >= 0 AND pay_amount >= 0)
);

COMMENT ON TABLE  orders                 IS '订单主表：一个订单一行（含已取消、已退款订单）';
COMMENT ON COLUMN orders.region_id       IS '[陷阱⑤] 收货地，与 dim_customer.region_id（注册地）是两回事。';
COMMENT ON COLUMN orders.order_time      IS '[陷阱⑧] 时间边界：是带时分秒的 TIMESTAMP。写 `order_time = ''2025-03-01''` 会隐式转成 00:00:00，只命中当天零点那一瞬间，结果接近 0。正确写法有 `>= ''2025-03-01'' AND < ''2025-04-01''` 或 `DATE(order_time)` 或 `date_trunc`。另外「近 7 天」要说清是否含今天。';
COMMENT ON COLUMN orders.order_status    IS '[陷阱⑥] 取值：completed / cancelled / pending / refunded。算任何销售额、销量、订单数时，如果不显式排除 cancelled，结果会系统性偏高约 12%。这是最高频的错，也是最容易在业务侧当场翻车的错。';
COMMENT ON COLUMN orders.total_amount    IS '[陷阱⑦] 吊牌价合计（未减优惠）。';
COMMENT ON COLUMN orders.discount_amount IS '[陷阱⑦] 优惠金额。';
COMMENT ON COLUMN orders.pay_amount      IS '[陷阱⑦] 实付金额。**故意构造成不等于 total_amount - discount_amount**，差额来自积分抵扣与运费。因此「销售额到底用哪个字段」是一个必须由语义层拍板的口径问题：财务口径用 pay_amount，GMV 口径用 total_amount。想当然地写 total - discount 也能跑，但数是错的。';
COMMENT ON COLUMN orders.channel         IS '下单渠道：app / web / mini_program / offline。';

CREATE INDEX idx_orders_time     ON orders (order_time);
CREATE INDEX idx_orders_status   ON orders (order_status);
CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_region   ON orders (region_id);
-- 组合索引：支撑"某时间段 + 某状态"这类最高频查询
CREATE INDEX idx_orders_time_status ON orders (order_time, order_status);


-- =============================================================================
-- 5. order_items · 订单明细表
-- =============================================================================
CREATE TABLE order_items (
    item_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT        NOT NULL,
    product_id  INT           NOT NULL,
    quantity    INT           NOT NULL,
    unit_price  NUMERIC(10,2) NOT NULL,
    item_amount NUMERIC(12,2) NOT NULL,

    CONSTRAINT fk_items_order   FOREIGN KEY (order_id)
        REFERENCES orders (order_id),
    CONSTRAINT fk_items_product FOREIGN KEY (product_id)
        REFERENCES dim_product (product_id),
    CONSTRAINT ck_items_qty     CHECK (quantity > 0)
);

COMMENT ON TABLE  order_items             IS '订单明细表：一个订单 N 行';
COMMENT ON COLUMN order_items.unit_price  IS '成交单价，通常低于 dim_product.list_price（吊牌价）。算「客单价」用 pay_amount / 订单数，算「件单价」用本列。';
COMMENT ON COLUMN order_items.item_amount IS '[陷阱⑩] 行金额 = quantity * unit_price，但 **SUM(item_amount) 与 orders.pay_amount 并不相等**：优惠被按比例分摊、有赠品行（unit_price=0）、有跨店满减。因此同一个「销售额」，
      (a) SUM(orders.pay_amount)   —— 财务实际收入
      (b) SUM(order_items.item_amount) —— 商品吊牌维度
      (c) SUM(orders.total_amount) —— GMV
      三者互不相等。选错就是口径错误，且不会报错。这就是为什么必须有语义层。';
COMMENT ON COLUMN order_items.quantity    IS '[陷阱⑨] 「销量」至少有三种口径：订单数 COUNT(DISTINCT order_id)、件数 SUM(quantity)、金额 SUM(item_amount)。用户说「卖得多」时，语义层必须先问清是哪一种。';

CREATE INDEX idx_items_order   ON order_items (order_id);
CREATE INDEX idx_items_product ON order_items (product_id);


-- =============================================================================
-- 6. refunds · 退款/退货表
-- =============================================================================
CREATE TABLE refunds (
    refund_id     BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT        NOT NULL,
    item_id       BIGINT,
    refund_time   TIMESTAMP     NOT NULL,
    refund_amount NUMERIC(12,2) NOT NULL,
    refund_reason VARCHAR(32)   NOT NULL,
    refund_status VARCHAR(16)   NOT NULL,

    CONSTRAINT fk_refunds_order FOREIGN KEY (order_id)
        REFERENCES orders (order_id),
    CONSTRAINT fk_refunds_item  FOREIGN KEY (item_id)
        REFERENCES order_items (item_id)
);

COMMENT ON TABLE  refunds               IS '退款表：整单退与部分退混存';
COMMENT ON COLUMN refunds.item_id       IS '[陷阱⑫] 可空外键。NULL 表示「整单退」，非 NULL 表示「指定明细退」。所以 `refunds JOIN order_items ON refunds.item_id = order_items.item_id` 会**静默丢掉所有整单退记录**（约 40%），产出一个看起来正常、实际偏低一半的退货率。这是 SQL 里最经典的"不报错的错"：必须用 LEFT JOIN 或分情况 UNION，并主动向用户声明口径。';
COMMENT ON COLUMN refunds.refund_status IS '[陷阱⑪] 取值：approved / pending / rejected。算退货率只能算 approved；把 pending/rejected 一起算会让退货率虚高。「退货率」本身还有三种分母：按订单数、按明细行数、按金额 —— 三种都能自圆其说，必须由语义层定义。';
COMMENT ON COLUMN refunds.refund_time   IS '退款发起时间，与 orders.order_time 可能跨月。按「退款月份」统计要小心与订单月份的口径差异。';

CREATE INDEX idx_refunds_order  ON refunds (order_id);
CREATE INDEX idx_refunds_item   ON refunds (item_id);
CREATE INDEX idx_refunds_time   ON refunds (refund_time);
CREATE INDEX idx_refunds_status ON refunds (refund_status);


-- =============================================================================
-- 7. 护栏第 1 层：只读数据库账号
-- -----------------------------------------------------------------------------
-- 三层护栏体系中的「权限层」：即使 LLM 生成了 DROP TABLE / UPDATE，
-- 数据库层面也直接拒绝，不依赖 Prompt 约束或字符串黑名单。
-- 这是最硬的一层，也是面试里最有说服力的一层（因为它不可被绕过）。
--
-- 注意：需要以超级用户执行本段，并把密码改为实际值。
-- =============================================================================
-- CREATE ROLE dataledger_ro WITH LOGIN PASSWORD '<REPLACE_ME>';
-- GRANT CONNECT ON DATABASE dataledger TO dataledger_ro;
-- GRANT USAGE   ON SCHEMA public      TO dataledger_ro;
-- GRANT SELECT  ON ALL TABLES IN SCHEMA public TO dataledger_ro;
-- ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO dataledger_ro;
-- REVOKE CREATE ON SCHEMA public FROM dataledger_ro;
-- 反向验证（应全部失败）：
--   UPDATE orders SET pay_amount = 0;   -- 期望: permission denied
--   DROP TABLE orders;                  -- 期望: must be owner of table


-- =============================================================================
-- 陷阱汇总（与 eval/cases.yaml 的 note 字段对应）
-- -----------------------------------------------------------------------------
--  ① dim_region.region_group 存「华东区」，用户说「华东」           → 等值匹配 0 行
--  ② dim_product 两级类目，选错列不报错但答案错                     → 静默错误
--  ③ dim_product.cost_price，算毛利必须跨表 join                    → 跨表口径
--  ④ dim_customer.birth_date 存生日不存年龄，且可 NULL              → 需换算 + NULL 处理
--  ⑤ 注册地 vs 收货地两个 region_id，约 15% 订单跨区                → 口径二义
--  ⑥ orders.order_status 含 cancelled，不排除则销售额虚高约 12%      → 分母污染
--  ⑦ 三个金额字段互不相等（差额来自积分与运费）                     → 口径二义
--  ⑧ order_time 带时分秒，等值比较命中 0 行                         → 边界错误
--  ⑨ 「销量」= 订单数 / 件数 / 金额 三种口径                        → 口径三义
--  ⑩ SUM(item_amount) ≠ SUM(pay_amount) ≠ SUM(total_amount)        → 口径三义
--  ⑪ 退货率：分母三种 × 状态三种，且订单月 ≠ 退款月                 → 口径多维
--  ⑫ refunds.item_id 可空，内连接静默丢 40% 整单退                  → 静默丢数
--
-- 一句话总结这份 Schema 的作用：
--   它把「Text-to-SQL 的准确率」从「模型能力问题」转化成了「工程口径问题」，
--   从而让「语义层 + 护栏 + 评测集」成为必需品，而不是炫技。
-- =============================================================================
